### ISSUE TITLE
Building cargo on ARM

### ISSUE THREAD

**Issue by japaric** [japaric/ruststrap#4]
- Some C dependencies pass `-m64` (which is not available in ARM) to gcc
  - [x] flate2-rs alexcrichton/flate2-rs#1
  - [x] curl-sys alexcrichton/curl-rust#2
  - [x] libssh2-static-sys alexcrichton/libssh2-static-sys#2
  - [x] libgit2 alexcrichton/git2-rs#13
- [x] Build cargo statically #6 
- ~~Patch `dl-snapshot.py` to fetch an unofficial nightly/snapshot~~
- [x] Create script to build cargo from an unofficial cargo nightly (using `--local-cargo`) 6274ba2
- [x] Update README
